### ISSUE TITLE
[BUG] Universe Actor don't Work Well After Duplicate

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#59] opened 2022-02-17 11:41 UTC
Hi!

I had to duplicate the universe to hide the factions from the group. But, The duplicate don't work well.

https://user-images.githubusercontent.com/4999783/154474284-5dd1bfae-c98e-4682-82b6-5c43b5cba113.mp4

**Comment by drewg13** [comment] 2022-02-19 14:21
I never considered that anyone would want multiple Universe actors.  I'm still not clear why you would need to do so, as FitD games are pretty open-information by design.  If your players are having trouble keeping things they know separate from things their characters know, it's going to be very difficult for them to help build the narrative.  I'll figure this one out though.

**Comment by drewg13** [comment] 2022-02-19 14:40
Got it, easy fix.

**Comment by drewg13** [comment] 2022-02-19 14:45
Fixed in 1.15.4

**Comment by brunocalado** [comment] 2022-02-19 14:47
I just want hide one faction because to surprise them.

Duplicate universe is more then that. Is hard to track faction locations, there was a GM doing that to organize faction by solar system.

**Comment by drewg13** [comment] 2022-02-19 16:06
Hmm, would it be more useful if the factions were attached the system tabs, rather than visible on the sheet as a whole?  That would be a simple enough change, I think.  But it also might be irritating to search through the tabs for a particular faction you have added somewhere.  My games have always tracked faction information by the whole sector, so it wouldn't occur to me to track it by system.  That would just be too much to track for me.

A different solution might be to modify the Universe actor sheet to make it cleaner to add/remove systems, so that you could more easily maintain the systems on different Universe actors, if you want.

Slightly more complex, but also not hard, would be to provide toggles for each faction to make it visible/invisible to non-GMs on a given sheet.

**Comment by drewg13** [comment] 2022-02-19 17:09
OK, I've got player-visibility toggles for systems, planets, and factions working.  Also removed the ability for players to delete those things, that just invites problems.  I really like how cleanly it works and can see the usefulness of it.

https://user-images.githubusercontent.com/1455026/154811131-c3a1831a-9355-4ff0-b58e-6bfaef2f0231.mp4

**Comment by drewg13** [comment] 2022-02-19 19:41
I've also reworked the sheet a bit to make it easier to add systems and planets on the fly.  This also makes it easy to build a separate Universe sheet for each System, if you prefer to track info that way.  The tabbed interface should only show up once you've added more than one System to a Universe sheet to cut down on interface clutter.  You can still use it the old automatically-populated all-on-one-sheet way, but this way adds additional flexibility, I think.

added in v1.16.0

**Closed by drewg13** 2022-02-19 19:41 UTC

**Comment by brunocalado** [comment] 2022-02-19 21:25
Very good. I like it a lot.

**Comment by brunocalado** [comment] 2022-02-19 21:27
> Hmm, would it be more useful if the factions were attached the system tabs, rather than visible on the sheet as a whole? That would be a simple enough change, I think. But it also might be irritating to search through the tabs for a particular faction you have added somewhere. My games have always tracked faction information by the whole sector, so it wouldn't occur to me to track it by system. That would just be too much to track for me.
> 
> A different solution might be to modify the Universe actor sheet to make it cleaner to add/remove systems, so that you could more easily maintain the systems on different Universe actors, if you want.
> 
> Slightly more complex, but also not hard, would be to provide toggles for each faction to make it visible/invisible to non-GMs on a given sheet.

I have no idea how to deal with the faction over system problem. This is a spreadsheet situation. Maybe add a color to the faction name when you enable a system where it has power.

https://docs.google.com/spreadsheets/d/1g8wWM3DhkIIYvDCgHqZlJ7kwnYyQbB8a4RgUawnZ3LY/edit#gid=0
![image](https://user-images.githubusercontent.com/4999783/154819630-7487db16-12f9-426c-b4d6-5ba6642ffe8a.png)
